/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type Milestone = {
  _type: 'milestone'
  value: string
  label: string
}

export type Merchant = {
  _type: 'merchant'
  name: string
  logo: ImageWithAlt
}

export type TeamMember = {
  _type: 'teamMember'
  name: string
  role: string
}

export type HeroSlide = {
  _type: 'heroSlide'
  eyebrow?: string
  headline: string
  image: ImageWithAlt
  ctaLabel: string
  ctaUrl?: string
  secondaryCtaLabel?: string
  secondaryCtaUrl?: string
}

export type EventLink = {
  _type: 'eventLink'
  label: string
  url: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type ImageWithAlt = {
  _type: 'imageWithAlt'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  publishedAt: string
  coverImage?: ImageWithAlt
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | ({
        _key: string
      } & ImageWithAlt)
  >
  orderRank?: string
}

export type Chapter = {
  _id: string
  _type: 'chapter'
  _createdAt: string
  _updatedAt: string
  _rev: string
  country: string
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  orderRank?: string
}

export type Event = {
  _id: string
  _type: 'event'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  status: 'upcoming' | 'past'
  datePrecision: 'full' | 'monthYear'
  date: string
  images?: Array<
    {
      _key: string
    } & ImageWithAlt
  >
  links?: Array<
    {
      _key: string
    } & EventLink
  >
  orderRank?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  status: 'ongoing' | 'completed'
  image: ImageWithAlt
  progress?: number
  date: string
  orderRank?: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  activeVolunteerUrl?: string
  donateUrl?: string
  whatsappUrl?: string
}

export type LoyaltyPage = {
  _id: string
  _type: 'loyaltyPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  merchants?: Array<
    {
      _key: string
    } & Merchant
  >
}

export type MembershipPage = {
  _id: string
  _type: 'membershipPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  poster: ImageWithAlt
  documentsRequired?: Array<string>
  payment?: {
    lifeMembership?: {
      label?: string
      badge?: string
      price?: string
    }
    replacementCard?: {
      label?: string
      price?: string
    }
  }
  ctaLabel?: string
  ctaUrl?: string
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type ProjectsPage = {
  _id: string
  _type: 'projectsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  dehiwala: {
    show?: boolean
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: ImageWithAlt
    highlightsLabel?: string
    highlightsUrl?: string
  }
  droneVideo?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  president: {
    name: string
    role: string
    photo?: ImageWithAlt
    message: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  team?: {
    year?: string
    patrons?: Array<
      {
        _key: string
      } & TeamMember
    >
    committee?: Array<
      {
        _key: string
      } & TeamMember
    >
  }
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero: {
    slides: Array<
      {
        _key: string
      } & HeroSlide
    >
  }
  aboutImage: ImageWithAlt
  milestones?: Array<
    {
      _key: string
    } & Milestone
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type AllSanitySchemaTypes =
  | Milestone
  | Merchant
  | TeamMember
  | HeroSlide
  | EventLink
  | SanityImageAssetReference
  | ImageWithAlt
  | Post
  | Chapter
  | Event
  | Project
  | SiteSettings
  | LoyaltyPage
  | MembershipPage
  | SanityFileAssetReference
  | ProjectsPage
  | AboutPage
  | HomePage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

// Source: src/sanity/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{  hero,  aboutImage,  milestones}
export type HomePageQueryResult = {
  hero: {
    slides: Array<
      {
        _key: string
      } & HeroSlide
    >
  }
  aboutImage: ImageWithAlt
  milestones: Array<
    {
      _key: string
    } & Milestone
  > | null
} | null

// Source: src/sanity/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{  president,  team}
export type AboutPageQueryResult = {
  president: {
    name: string
    role: string
    photo?: ImageWithAlt
    message: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
  }
  team: {
    year?: string
    patrons?: Array<
      {
        _key: string
      } & TeamMember
    >
    committee?: Array<
      {
        _key: string
      } & TeamMember
    >
  } | null
} | null

// Source: src/sanity/queries.ts
// Variable: projectsPageQuery
// Query: *[_type == "projectsPage"][0]{  dehiwala,  "droneVideo": droneVideo.asset->{url, mimeType}}
export type ProjectsPageQueryResult = {
  dehiwala: {
    show?: boolean
    title: string
    body?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    image: ImageWithAlt
    highlightsLabel?: string
    highlightsUrl?: string
  }
  droneVideo: {
    url: string
    mimeType: string
  } | null
} | null

// Source: src/sanity/queries.ts
// Variable: membershipPageQuery
// Query: *[_type == "membershipPage"][0]{  poster,  documentsRequired,  payment,  ctaLabel,  ctaUrl}
export type MembershipPageQueryResult = {
  poster: ImageWithAlt
  documentsRequired: Array<string> | null
  payment: {
    lifeMembership?: {
      label?: string
      badge?: string
      price?: string
    }
    replacementCard?: {
      label?: string
      price?: string
    }
  } | null
  ctaLabel: string | null
  ctaUrl: string | null
} | null

// Source: src/sanity/queries.ts
// Variable: loyaltyPageQuery
// Query: *[_type == "loyaltyPage"][0]{  merchants}
export type LoyaltyPageQueryResult = {
  merchants: Array<
    {
      _key: string
    } & Merchant
  > | null
} | null

// Source: src/sanity/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  activeVolunteerUrl,  donateUrl,  whatsappUrl}
export type SiteSettingsQueryResult = {
  activeVolunteerUrl: string | null
  donateUrl: string | null
  whatsappUrl: string | null
} | null

// Source: src/sanity/queries.ts
// Variable: chaptersQuery
// Query: *[_type == "chapter"] | order(orderRank asc){  _id,  country,  description,  images}
export type ChaptersQueryResult = Array<{
  _id: string
  country: string
  description: null
  images: Array<
    {
      _key: string
    } & ImageWithAlt
  > | null
}>

// Source: src/sanity/queries.ts
// Variable: projectsByStatusQuery
// Query: *[_type == "project" && status == $status] | order(orderRank asc){  _id,  title,  status,  image,  description,  progress,  date}
export type ProjectsByStatusQueryResult = Array<{
  _id: string
  title: string
  status: 'completed' | 'ongoing'
  image: ImageWithAlt
  description: null
  progress: number | null
  date: string
}>

// Source: src/sanity/queries.ts
// Variable: upcomingEventsQuery
// Query: *[_type == "event" && status == "upcoming"] | order(orderRank asc){  _id,  title,  date,  datePrecision,  description,  images,  links}
export type UpcomingEventsQueryResult = Array<{
  _id: string
  title: string
  date: string
  datePrecision: 'full' | 'monthYear'
  description: null
  images: Array<
    {
      _key: string
    } & ImageWithAlt
  > | null
  links: Array<
    {
      _key: string
    } & EventLink
  > | null
}>

// Source: src/sanity/queries.ts
// Variable: pastEventsQuery
// Query: *[_type == "event" && status == "past"] | order(orderRank asc){  _id,  title,  date,  datePrecision,  description,  images,  links}
export type PastEventsQueryResult = Array<{
  _id: string
  title: string
  date: string
  datePrecision: 'full' | 'monthYear'
  description: null
  images: Array<
    {
      _key: string
    } & ImageWithAlt
  > | null
  links: Array<
    {
      _key: string
    } & EventLink
  > | null
}>

// Source: src/sanity/queries.ts
// Variable: postsQuery
// Query: *[_type == "post"] | order(orderRank asc){  _id,  title,  publishedAt,  coverImage}
export type PostsQueryResult = Array<{
  _id: string
  title: string
  publishedAt: string
  coverImage: ImageWithAlt | null
}>

// Source: src/sanity/queries.ts
// Variable: postByIdQuery
// Query: *[_type == "post" && _id == $id][0]{  _id,  title,  publishedAt,  coverImage,  body}
export type PostByIdQueryResult = {
  _id: string
  title: string
  publishedAt: string
  coverImage: ImageWithAlt | null
  body: Array<
    | ({
        _key: string
      } & ImageWithAlt)
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
  > | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "homePage"][0]{\n  hero,\n  aboutImage,\n  milestones\n}': HomePageQueryResult
    '*[_type == "aboutPage"][0]{\n  president,\n  team\n}': AboutPageQueryResult
    '*[_type == "projectsPage"][0]{\n  dehiwala,\n  "droneVideo": droneVideo.asset->{url, mimeType}\n}': ProjectsPageQueryResult
    '*[_type == "membershipPage"][0]{\n  poster,\n  documentsRequired,\n  payment,\n  ctaLabel,\n  ctaUrl\n}': MembershipPageQueryResult
    '*[_type == "loyaltyPage"][0]{\n  merchants\n}': LoyaltyPageQueryResult
    '*[_type == "siteSettings"][0]{\n  activeVolunteerUrl,\n  donateUrl,\n  whatsappUrl\n}': SiteSettingsQueryResult
    '*[_type == "chapter"] | order(orderRank asc){\n  _id,\n  country,\n  description,\n  images\n}': ChaptersQueryResult
    '*[_type == "project" && status == $status] | order(orderRank asc){\n  _id,\n  title,\n  status,\n  image,\n  description,\n  progress,\n  date\n}': ProjectsByStatusQueryResult
    '*[_type == "event" && status == "upcoming"] | order(orderRank asc){\n  _id,\n  title,\n  date,\n  datePrecision,\n  description,\n  images,\n  links\n}': UpcomingEventsQueryResult
    '*[_type == "event" && status == "past"] | order(orderRank asc){\n  _id,\n  title,\n  date,\n  datePrecision,\n  description,\n  images,\n  links\n}': PastEventsQueryResult
    '*[_type == "post"] | order(orderRank asc){\n  _id,\n  title,\n  publishedAt,\n  coverImage\n}': PostsQueryResult
    '*[_type == "post" && _id == $id][0]{\n  _id,\n  title,\n  publishedAt,\n  coverImage,\n  body\n}': PostByIdQueryResult
  }
}
